FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine 

WORKDIR /app
COPY package*.json ./
ENV PORT=3001
ENV NODE_ENV=Production
RUN npm install

COPY --from=builder /app/dist ./dist
EXPOSE ${PORT}

CMD ["npm", "run", "start:prod"]